app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<str:blog_id>', views.detail, name='detail')
]

app/blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/img')
    url = models.URLField(blank=True) #open in new page
    date = models.DateField(default='')

    def __str__(self):
        return self.title

app/portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=9999)
    image = models.ImageField(upload_to='portfolio/img')
    url = models.URLField(blank=True)  # open in new page
    tech = models.JSONField()

    def __str__(self):
        return self.title

app/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blog = Blog.objects.all()
    return render(request, 'blog/all_blogs.html', {'blog': blog})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'id': blog})

app/portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

app/blog/templates/blog/all_blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hello blogs!</h1>
    {% for i in blog %}
        {{ i.description }}
        <br>
        <img src="{{ i.image.url }}" style="width: 550px; height: auto;"><br>
        {% if i.url %}
            <br>
            <a href="{{ i.url }}">link</a>
        {% endif %}
    {% endfor %}
</body>
</html>

app/blog/templates/blog/detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>{{ id.description }}</h1>
</body>
</html>

app/portfolio/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'portfolio/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/bootstrap.min.css' %}" >
    <title>Document</title>
</head>
<body>

<header class="d-flex flex-wrap justify-content-between py-3 mb-4 border-bottom">
  <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
    <span class="fs-4" style="margin:0 auto 0 15px; font-size: 21px">Mack's portfolio</span>
  </a>

  <ul class="nav nav-pills">
    <li class="nav-item"><a href="#" class="nav-link">Home</a></li>
    <li class="nav-item"><a href="https://github.com/rublock" class="nav-link">Github</a></li>
    <li class="nav-item"><a href="https://github.com/rublock" class="nav-link">CV download</a></li>
    <li class="nav-item"><a href="{% url 'blog:all_blogs' %}" class="nav-link">Blog</a></li>
  </ul>
</header>

{% block content %}{% endblock %}

<script src="{% static 'portfolio/js/bootstrap.min.js' %}"></script>
</body>
</html>

app/portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load static %}
{% block content %}

<div class="cardContainer">
    {% for i in projects %}
    <div class="square">
        <img src="{{ i.image.url }}" class="mask">
        <div class="title">{{ i.title }}</div>
        <p class="description">{{ i.description }}</p>
            <div class="skillsContainer">
                {% for v in i.tech.values %}
                <a class="skills badge bg-light text-dark h-50 border border-dark">{{ v }}</a>
                {% endfor %}
            </div>
<!--        <div><a href="{% url 'blog:all_blogs' %}" class="button">Открыть</a></div>-->
    </div>
    {% endfor %}
</div>


{% endblock %}